### ISSUE TITLE
Number of tweets returned exceeds the tweet count requested

### ISSUE THREAD

**Issue by RizwanNida** [vosonlab/VOSONDash#6]
Hi, I used VosonDashboard 0.3.4 to collect tweets. Instructed to get 18000 tweets but it returned 29000. How did this happen?

**Comment by mishoryu** [comment]
Hi @RizwanNida, thanks for the question and apologies that this behaviour is not better documented. It occurs because of how the underlaying twitter package that is used by `vosonSML` functions when more tweets are requested than are available in the current rate limit.

The standard twitter API sets a search rate limit that translates to 18000 tweets that can be collected every 15 minutes. As can be seen in the image you provided 18000 tweets were requested but only 11500 are available to be collected in the current rate limit window (that will reset at 11:56PM). This was likely due to smaller collections being performed just beforehand.

When more tweets are requested than are available in the current rate limit it automatically activates an underlying package feature called `retryOnRateLimit`. This feature pauses the tweet collection when the rate limit is reached and waits until it resets before resuming. The collection you performed likely would have taken around 12 - 15 minutes as the software waited for the rate limit to reset after collecting the first 11500 tweets.

This feature was designed with large scale collections in mind and when activated can end up collecting up to 18000 more tweets than expected. This is because when activated it switches to collecting tweets in 18000 tweet windows rather than using a precise count. For example, if you wanted to collect 38000 tweets you may end up collecting a maximum of `38000 / 18000 = 3 (2.1 rounded up) * 18000 = 54000 tweets`. In this example there would be 2 pauses to wait for the rate limit to reset.

In the example you provided you requested 18000 tweets with only 11500 available activating the `retryOnRateLimit` feature. This means a maximum of `(11500 +)  18000 / 18000 = 1 * 18000 = 29500 tweets` with 1 pause as the rate limit resets. As the maximum was not reached it is likely that there were only 29234 tweets available to be returned from the twitter API for this search.

The option to choose if `retryOnRateLimit` is used will probably be added to `VOSONDash` but there are no plans to make it more precise at this stage.

**Comment by RizwanNida** [comment]
Thank you for the reply.
