### ISSUE TITLE
VosonDash fails to launch in R 

### ISSUE THREAD

**Issue by karlgwynn** [vosonlab/VOSONDash#8]
When trying to launch VosonDash, the same error message prints:

Warning: Error in $: $ operator is invalid for atomic vectors
  54: tag
  53: tags$section
  49: dashboardBody

This occurs on multiple computers and it hasn't been resolved by restarting or reopening.

**Comment by mishoryu** [comment]
Hi karlgwynn, thanks for submitting this issue. It's an odd problem that seems to be due to some code or the order of some code that we pass to a package we use in our app called `shinydashboard`. This problem doesn't occur for everyone unfortunately, and I'm unable to duplicate it at this time which makes it difficult to find the cause.

If possible could you download and try the new version of `VOSONDash` version `0.3.8` from:
[https://github.com/vosonlab/VOSONDash/archive/master.zip](https://github.com/vosonlab/VOSONDash/archive/master.zip)

This version writes to the R console some R and package information when the app starts. If you encounter the same error and could copy and respond with the information from your console that would be a great help.

The information should be similar to the following:
```R
VOSONDash v0.3.8 04 May 19
05 May 2019 01:49

x86_64-apple-darwin15.6.0
R version 3.6.0 (2019-04-26)
R shiny 1.3.2

Checking packages...
Found all required packages.
- htmlwidgets [1.3]
- shinydashboard [0.7.1]
- shinyjs [1.0]

...

- dplyr [0.8.0.1]
- httr [1.4.0]
- vosonSML [0.26.3]

Starting VOSONDash...
```
Thanks for your help.

**Comment by karlgwynn** [comment]
I've gone through and updated R and VOSONDash. Attempting to run VOSONDash produced this: 

VOSONDash v0.3.8 04May19
05 May 2019 12:39

Windows_NT x86_64-w64-mingw32
R version 3.6.0 (2019-04-26)
R shiny 1.3.2

Checking packages...
Found all required packages.
- htmlwidgets [1.3]
- shinydashboard [0.7.1]
- shinyjs [1.0]
- DT [0.5]
- networkD3 [0.4]
- visNetwork [2.0.6]
- igraph [1.2.4.1]
- SnowballC [0.6.0]
- tm [0.7.6]
- lattice [0.20.38]
- RColorBrewer [1.1.2]
- wordcloud [2.6]
- syuzhet [1.0.4]
- dplyr [0.8.0.1]
- httr [1.4.0]
- vosonSML [0.26.3]

Starting VOSONDash...

Listening on http://127.0.0.1:5948
Warning: Error in $: $ operator is invalid for atomic vectors
  54: tag
  53: tags$section
  49: dashboardBody

Still no luck getting it running.

**Comment by mishoryu** [comment]
Thanks very much for that. Just a further few questions, which version of RStudio are you using? Do you save your environment between sessions? and do you use the built-in RStudio browser or an external browser to view `VOSONDash`? (e.g Chrome)

It might be worth trying a `Session > Clear Workspace...` including hidden objects and `Session > Restart R` making sure nothing is loaded in the environment before you start `VOSONDash`. If you made a project for `VOSONDash` in RStudio, you might also try deleting that and making a new one. I'm not sure if it will make any difference in this circumstance but `VOSONDash` also works best and is more feature rich in an external viewer.

Sorry for the questions and follow up, it's difficult when I can't debug the problem myself.

**Comment by karlgwynn** [comment]
Your suggestion to clear workspace and restart R succeeding in allowing it to run. Thank you for your assistance in resolving the issue.
